# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17d5e0d85e7ba36fe5f9f6773083bd1e9fe790072b5f95261b43e41a2d74dba0fb98bc7993a27eeb6a7785754005f58d2b0d8d18ce3f706daabb79b9fc9cb05e

test:
  secret_key_base: c378585a2a4de1051e68deecf41c28be11c6e3f3433fadb0220998fd02820e5b7824973b0f4626555b64d3f7b69f947945a1b9627c314a6ac2123c2fd198de39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
